csvExporter.py
Originally was just adding the conditions for between and not between but turns out none of the number field conditions were added.
=> [ICOLLECT-528] Add number smart fields

csvExporter.py
a959ec5 support note from all items (read from property `responses.text` for question/list as before, `responses.note` for others)
a1e8620 allow signature and drawing to append image + additional media
=> [ICOLLECT-565] note and media on all items

internal/app/feed/feed_schedule_assginee.go, internal/app/feed/mocks/set_1/feed_schedule_assignees_1.json, internal/app/feed/mocks/set_1/outputs/schedule_assignees.csv, internal/app/feed/mocks/set_2/feed_schedule_assignees_1.json, internal/app/feed/mocks/set_2/outputs/schedule_assignees.csv
`schedule_assginees` format was changed to provide unique IDs. This revises the schema to support that.
=> [INTG-1532] Updates schedule_assginees to revised format

.goreleaser.yml
Draft releases by default and mark prereleases as prereleases
=> Draft releases by default and mark prereleases as prereleases

.pre-commit-config.yaml, README.md
Adds instructions on how to release a new version
=> Add instructions for releasing

README.md
Added docs for exporting to SQL DBs and also listing available table schemas.
=> INTG-1523: add docs for sql connections

README.md
Changed config documentation form tabular to list format.
=> INTG-1550: fix config table

README.md
After going through current support page I added a few sections that were missing from current README page.
=> INTG-1572: update readme to match current support page

README.md, cmd/iauditor-exporter/cmd/root.go, docs/iauditor-exporter_csv.md, docs/iauditor-exporter_sql.md, internal/app/api/api.go, internal/app/feed/export_feeds.go, internal/app/feed/export_feeds_test.go, internal/app/feed/feed_site.go, internal/app/feed/mocks/set_1/feed_sites_1.json, internal/app/feed/mocks/set_1/outputs/sites.csv, internal/app/feed/mocks/set_1/schemas/formatted/sites.txt, internal/app/feed/mocks/set_1/schemas/sites.csv, internal/app/feed/mocks/set_2/outputs/sites.csv
A new flag 'site-include-deleted' option is added to include deleted sites.
=> [INTG-1600] Add deleted flag to sites and optionally return deleted sites

README.md
Add some more notes about where to find the older version of iAuditor Exporter
=> Add bolder note about the old python connector

README.md, cmd/iauditor-exporter/cmd/root.go
- Updated default filter to only completed inspections.
- Fix some readme inconsistencies
=> [INTG-1646] Update default filter to only completed inspections

README.md
Adds actions to the top of the readme
=> Add actions to readme

cmd/iauditor-exporter/cmd/root.go
Removes the startup disclaimer
=> Remove disclaimer on startup

cmd/iauditor-exporter/cmd/root.go
I'm still unable to figure out the exact reason why it is not working with the previous code.
=> [INTG-1664] Config-path flag is not working

internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_template_permission.go, internal/app/feed/feed_user.go
Improve the log message, so that we can understand for which endpoint it has failed.
=> [INTG-1683] Improve log messages in iauditor-exporter

internal/app/exporter/exporter.go, internal/app/exporter/exporter_json.go, internal/app/exporter/exporter_json_test.go, internal/app/exporter/mocks/exporter_mock.go, internal/app/inspections/inspections.go, internal/app/inspections/inspections_test.go
There was a bug in the implementation of the logic.
Modified the logic and added a test case to test the scenario.
=> [INTG-1670] Modified_after not being respected in json export

cmd/iauditor-exporter/cmd/root.go
Changed "filename" to "filename-convention" in bingFlags
=> [INTG-1762] fixed BindPFlag

internal/app/exporter/exporter_json.go, internal/app/exporter/exporter_json_test.go
This can happen if the older timestamp contained nano seconds and the new one didn't. The saved timestamp can end up malformed like `2021-05-18T15:17:41.1Z6Z`
=> [PROBLEM-901] Handle saving `last-modified` at file when string is shorter than older string

.goreleaser.yml, .pre-commit-config.yaml, THIRD_PARTY_NOTICES.md
Manually generated from a script using https://github.com/google/go-licenses. I'll look at incorporating this into our GitHub bot next to automatically generate this notices file.
=> [INTG-1676] Create third party notices file

internal/app/exporter/exporter_json_test.go, internal/app/feed/exporter_csv.go, internal/app/feed/exporter_csv_test.go, internal/app/feed/exporter_report.go, internal/app/feed/exporter_sql.go, internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_group.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_user.go, internal/app/feed/utils_test.go, internal/app/inspections/inspections.go
Fixed `Go Code Review` issues in this repo.
=> INTG-1888: fix code review issues

internal/app/feed/feed_group_user.go, internal/app/feed/mocks/set_2/feed_group_users_1.json, internal/app/feed/mocks/set_2/outputs/group_users.csv
Added upset support for group_user
=> PROBLEM-1292_iAuditor Exporter - group_users table not working with multiple orgs

internal/app/feed/feed_issue.go, internal/app/feed/mocks/set_1/outputs/issues.csv, internal/app/feed/mocks/set_1/schemas/issues.csv, internal/app/feed/mocks/set_2/outputs/issues.csv
CVS column name fixed from CreatorUserName to creator_user_name
=> INTG-2143 correct the csv column name

README.md
Update the documentation (readme file) to have reference to the new Issues Feed.
NOTE: this will be merged after WIKI has been updated so the link will be valid
=> [INTG-2165] add reference to the wiki for Issues

Makefile
Reverting the goreleaser docker image
=> [INTG-2169] revert goreleaser

Makefile
update go-releaser to the new version
=> INTG-2169 revert goreleaser

.github/workflows/goreleaser.yml
update GitHub permissions for publishing docker image
=> INTG-2169 update permissions for token

.github/workflows/goreleaser.yml, Makefile
=> INTG-2169 pass docker arguments

.github/workflows/goreleaser.yml, Makefile
use docker login in GitHub actions
=> INTG-2169 docker login

Makefile, README.md
GORELEASER 1.18 was not using GO ver 1.18 ...
=> INTG-2277 fixed go-releaser version

internal/app/api/api.go, internal/app/api/api_test.go
Add extra login message when request is failing with a message
=> INTG-2366 add extra logging messages

ui/frontend/src/App.svelte, ui/frontend/src/components/debug.svelte, ui/frontend/src/lib/store.js, ui/frontend/src/routes/FeedFilter.svelte, ui/frontend/src/routes/Init.svelte, ui/frontend/src/routes/TemplateFilter.svelte, ui/frontend/src/routes/Welcome.svelte
implement a store for configuration
=> INTG-2571 config store

pkg/api/configuration_manager.go, pkg/api/exporter_api.go, pkg/api/models.go, pkg/internal/inspections/inspections.go, pkg/internal/templates/fixtures/page_1_of_3.json, pkg/internal/templates/fixtures/page_2_of_3.json, pkg/internal/templates/fixtures/page_3_of_3.json, pkg/internal/templates/fixtures/single_page_success.json, pkg/internal/templates/get_template_list.go, pkg/internal/templates/get_template_list_test.go, pkg/internal/util/mapper.go
Call the new end endpoint search templates, self-paginate and return the responses
=> INTG-2550 drain fn for GetTemplates

pkg/api/exporter_api_test.go, pkg/api/models.go, pkg/internal/templates/get_template_list.go
=> INTG-2550 change field names and new test

.pre-commit-config.yaml, pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/api/fixtures/corrupted_configuration.yaml
This PR aims to have protection when file is empty
=> INTG-2582 regenerate configuration

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
this PR will make sure will apply the safe defaults if the file was empty or new
=> INTG-2582 apply defaults

README.md, cmd/safetyculture-exporter/cmd/export/export.go
This PR will fix a bug where sheqsy export was not triggered when customer had no API_KEY
=> INTG-2574 export sheqsy

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
This PR aims to provide defaults for a few config options like CSV/SQL, Include Archived ...
=> INTG-2588 provide defaults

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/api/fixtures/valid_with_time_long.yaml
Read/Write ISO8601 times from YAML file
=> INTG-2593 parse tz iso8601

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/internal/util/time_utils.go, pkg/internal/util/time_utils_test.go
=> INTG-2596 accept all time formats

cmd/safetyculture-exporter/cmd/export/export.go, cmd/safetyculture-exporter/cmd/root.go, internal/app/version/version.go, internal/app/version/version_test.go, pkg/api/configuration_manager.go, pkg/api/exporter_api.go, pkg/api/exporter_api_test.go, pkg/api/utils_test.go, pkg/httpapi/httpapi.go, pkg/httpapi/httpapi_test.go, pkg/internal/feed/get_feed.go, pkg/internal/feed/inspection_media.go, pkg/internal/feed/org_activity.go, pkg/internal/feed/sheqsy.go, pkg/internal/inspections/get_inspection.go, pkg/internal/inspections/list_inspections.go, pkg/internal/report/download_inspection_report.go, pkg/internal/report/inspection_report_check.go, pkg/internal/report/inspection_report_export.go, pkg/internal/templates/get_template_list.go, pkg/internal/templates/get_template_list_test.go, pkg/logger/logger.go
This PR aims to allow passing version as argument
=> INTG-2563 versioning

pkg/api/exporter_api.go
UI now can update the configuration
=> INTG-2610 fix save conf

pkg/api/exporter_api.go, pkg/api/exporter_api_test.go, pkg/internal/templates/get_template_list.go, pkg/internal/templates/get_template_list_test.go
when error, return only what was downloaded
=> INTG-2615 gracefull templates

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/api/exporter_api_test.go, pkg/api/utils_test.go, pkg/internal/templates/get_template_list_test.go, pkg/internal/util/time_utils.go
This PR will set the default export time to 1 year ago when the export time is missing from the configuration
=> INTG-2623 default start time

.codeclimate.yml, cmd/safetyculture-exporter/cmd/root.go, pkg/update/update.go, pkg/update/update_test.go
Extend the existing version check so can be used by the UI as well
=> INTG-2621 version check

README.md
Removed the warning in the ReadMe file
=> remove readme warning

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
=> INTG-2622 change the path for export and media

pkg/api/exporter_api.go, pkg/internal/feed/exporter_sql.go
Refactored code to allow for checking the db connection from the UI beforehand.
=> INTG-2627 - Refactored code to allow for checking the db connection.

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/update/update.go, pkg/update/update_test.go
this PR:
- Change windows binary file name from `amd64` to `x86_64`
- update path and media path in default yaml to [working directory + export]
=> INTG-2655 change defaults path to working dir

pkg/internal/feed/exporter_report.go
=> INTG-2630 count down

.github/workflows/goreleaser.yml, Makefile, go.mod
=> INTG-2674 upgrade go

.github/workflows/goreleaser.yml, Makefile, go.mod
=> INTG-2674 Rollback GoUPG

pkg/api/mocks/set_1/feed_actions_1.json, pkg/api/mocks/set_1/outputs/actions.csv, pkg/api/mocks/set_2/outputs/actions.csv, pkg/internal/feed/feed_action.go, pkg/internal/feed/fixtures/schemas/formatted/actions.txt
this PR:
- support for action label in actions feed
=> INTG-2578 actions feed - add action labels

cmd/safetyculture-exporter/cmd/export/export.go, cmd/safetyculture-exporter/cmd/root.go, pkg/api/exporter_api.go, pkg/internal/feed/exporter_sql.go
Added SQLITE as export option
Pros: re-used SQLExporter
Cons: a little bit of duplicated code to initialise the exporter
=> INTG-2684 added sqlite option

pkg/update/update.go, pkg/update/update_test.go
Update version parser for windows
=> INTG-2698 adapt version

pkg/api/drain_inspections_test.go, pkg/internal/inspections/drain_inspections.go, pkg/internal/inspections/inspections.go
make json export print logs
there was no progress indication
---
=> INTG-2535 add logs for json export

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
Use relative paths instead of full paths
The application can be moved to a different folder
---
=> INTG-2699 use rel path

pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
When the modifiedAfter was missing, we were defaulting for past year. Now we removed that limitation
---
=> INTG-2750 modifiedAfter

go.mod, go.sum, pkg/internal/feed/feed_action_assignees.go, pkg/internal/util/slice.go, pkg/internal/util/slice_test.go
Fixes the way batch indexing was working
Refactors the batch itself because it's used in many places
Collecting ActionsID was done wrong, allowing duplicates 
---
=> INTG-2800 fix batch in assignees

.github/workflows/tests.yml, go.mod, pkg/logger/logger.go
This PR changes the log layout from logs.log to sc-exporter-yyyy-MM-dd.logs
Customers are currently having all their logs lumped into one log file, creating confusion.
---
=> [INTG-2805] Adding date to the log

pkg/api/export_feeds_test.go, pkg/internal/feed/feed_action.go, pkg/internal/feed/feed_action_timeline_item.go, pkg/internal/feed/feed_asset.go, pkg/internal/feed/feed_group.go, pkg/internal/feed/feed_group_user.go, pkg/internal/feed/feed_inspection.go, pkg/internal/feed/feed_inspection_item.go, pkg/internal/feed/feed_issue.go, pkg/internal/feed/feed_issue_timeline_item.go, pkg/internal/feed/feed_schedule.go, pkg/internal/feed/feed_schedule_assignee.go, pkg/internal/feed/feed_schedule_occurrence.go, pkg/internal/feed/feed_sheqsy_activity.go, pkg/internal/feed/feed_sheqsy_department.go, pkg/internal/feed/feed_sheqsy_department_employee.go, pkg/internal/feed/feed_sheqsy_employee.go, pkg/internal/feed/feed_sheqsy_shift.go, pkg/internal/feed/feed_site.go, pkg/internal/feed/feed_site_member.go, pkg/internal/feed/feed_template.go, pkg/internal/feed/feed_template_permission.go, pkg/internal/feed/feed_user.go, pkg/internal/util/time_utils.go, pkg/internal/util/time_utils_test.go
Replace a section that was repeated in every feed with a single tested construct
Code simplification
---
=> INTG-2802 replace duplicated slice

cmd/safetyculture-exporter/cmd/export/export.go, cmd/safetyculture-exporter/cmd/root.go, pkg/api/configuration_manager.go, pkg/internal/feed/feed_exporter.go
allow the customer to lower the max-concurrency levels (might help prevent the sqlite locking)
---
=> INTG-2821 configure the concurrency

pkg/internal/feed/feed_issue.go, pkg/internal/feed/feed_issue_timeline_item.go, pkg/internal/feed/feed_status.go, pkg/internal/feed/feed_training_course_progress.go
Better logs for issues
issues* feed don't have `remaining items` information
- ...
---
=> INTG-3044 feed issues will send the correct status in the logs

pkg/api/exporter_csv_test.go, pkg/api/mocks/set_1/feed_users_1.json, pkg/api/mocks/set_1/outputs/users.csv, pkg/api/mocks/set_1/schemas/formatted/users.txt, pkg/api/mocks/set_1/schemas/users.csv, pkg/api/mocks/set_2/outputs/users.csv, pkg/internal/feed/feed_user.go, pkg/internal/feed/fixtures/schemas/formatted/users.txt
Add SeatType to the user feed
- ...
---
=> INTG-3202 add seat type

pkg/internal/feed/feed_issue_assignee.go
This PR fixes the column length for 3 fields and adds indexes as they were missing.
- ...
---
=> INTG-3363 - Fixed column length and added indexes.

pkg/internal/feed/exporter_sql.go
=> INTG-3379 - Synchronize writes to avoid database locking

pkg/internal/feed/exporter_csv.go, pkg/internal/feed/feed_status.go
modifies the CSV export to send incremental data
- ...
---
=> DEVP-3419 csv counter incremental

pkg/internal/feed/feed_action_assignees.go, pkg/internal/feed/feed_exporter.go
the feed times out for a customer using page size of 1000.
Set the exported default to 100
- ...
---
=> PROBLEM-3623 limit page size to 100

.github/workflows/build.yml
Replaces ubuntu-latest with the LTS
- ...
---
=> DEVP-3557 fixed ubuntu ver
