SafetyCulture/safetyculture-exporter

.github/workflows/tests.yml, Makefile, README.md, cmd/iauditor-exporter/cmd/export/export.go, docker-compose.yml, internal/app/feed/export_feeds_test.go, internal/app/feed/exporter_csv.go, internal/app/feed/exporter_sql.go, internal/app/feed/exporter_sql_intg_test.go, internal/app/feed/exporter_sql_test.go
This PR adds integration tests that run against the 3 support SQL Databases for iAuditor Exporter. 
The test suite is extremely basic at the moment and will be expanded in a subsequent PR.
Also added a section in the README to run the tests locally.
=> [INTG-1521] Add basic SQL integration tests against DBs

internal/app/api/api.go, internal/app/feed/export_feeds_intg_test.go, internal/app/feed/exporter_csv_test.go, internal/app/feed/exporter_sql_intg_test.go, internal/app/feed/exporter_sql_test.go, internal/app/feed/feed_inspection_test.go, internal/app/feed/utils_test.go
This PR adds integration tests for SQL databases. You might notice that these look like they are testing CSV exporting... Well that is because they are! These tests leverage the fact that our CSV exporter wraps our SQLExporter and uses a file based SQLite DB to perform incremental refreshes.
Instead of using that SQLite DB, we just use a real one. Simple as that, we have tested our ability to export to a SQL DB, and comparing the output is as easy as comparing 2 CSV files.
Also moves some test utils around and removes some debugging statements.
=> [INTG-1521] Add integration tests for SQL databases

Makefile, internal/app/feed/export_feeds_soak_test.go, internal/app/feed/exporter_sql.go, internal/app/feed/feed.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_user.go, internal/app/feed/mocks/set_1/feed_schedule_occurrences_1.json, internal/app/feed/mocks/set_1/outputs/schedule_occurrences.csv, internal/app/feed/mocks/set_2/outputs/schedule_occurrences.csv, internal/app/feed/utils_test.go
Different databases have different limits on the number of parameters they can support in a single query.
Feeds now use this to calculate the number of rows they can insert in any given query.
=> [INTG-1557] Add improved handling of different Database parameter limits

cmd/iauditor-exporter/cmd/configure/configure.go, cmd/iauditor-exporter/cmd/root.go
These changes will make it more clear when the config file is being created or updated.
Creating a new config file:
When config file exists:
I also spent some time trying to add comments to the config file. This is not a trivial task. Config file is created by `viper` and it doesn't support comments at the moment. One option is to make changes to viper and add support for comments. But this is going to be a big overtaking due to the fact that viper supports many configuration formats (yaml, json and ...).
Another option is to have an example file with all the comments and copy that. This has a few downsides:
- Viper won't create/update the config
- Users cannot update the config file using command line flags anymore
- If flags are created/updated we have to make sure those changes are …
=> INTG-1551: clean up config command

.github/dependabot.yml
Added commit message prefix to `dependabot.yml `. This will fix `SafetyTravis` error message for not having a Jira ticket.
=> INTG-1566: add commit message prefix to dependabot config

cmd/iauditor-exporter/cmd/root.go
`configure` command was added to the list of commands twice. This will remove one instance.
=> INTG-1614: remov duplicate configure command

.github/workflows/goreleaser.yml, .github/workflows/security-scan.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, internal/app/feed/exporter_sql.go, internal/app/feed/exporter_sql_intg_test.go
It looks like gorm is adding a default sort by the primary key to all queries. It thinks that ModifiedAt is the primary key as it is the only one present in the model.
Adding ExportedAt first makes this the default sort. It was chosen as it is present on all tables.
=> [INTG-1618] Fix exporting breaking when performing incremental exports against SQL Server

internal/app/exporter/exporter_json.go, internal/app/exporter/exporter_json_test.go
Figured out last-modified timestamp from file is getting ignored when we restart the export.
=> [INTG-1636] Inspection json export ignoring last modified timestamp

internal/app/feed/exporter_csv_test.go, internal/app/feed/exporter_sql.go, internal/app/feed/exporter_sql_intg_test.go, internal/app/feed/exporter_sql_test.go, internal/app/feed/feed.go, internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_template.go, internal/app/inspections/inspections.go
This allows ModifiedAfter to be updated mid run and still take effect.
=> [INTG-1647] Add handling for when modified_after is later than modified_at

internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_template_permission.go, internal/app/feed/feed_user.go
Inserts actions in batches to the DB. This impacts SQL Server predominantly as it can only support 2100 parameters in a single query.
=> [INTG-1656] Insert actions in batches to the DB

internal/app/api/api.go, internal/app/api/api_test.go, internal/app/feed/utils_test.go
Adds additional logging to the request flows to ensure we can debug failed requests.
=> [CPR-2302] Add additional logging to request flows

README.md
The README needs to be updated with the following goals in mind:
*   Reflect the previous support article version for the iAuditor Exporter written in Python.
*   Make sure to NOTE clearer that the version is no longer supported and direct customers to the new version as much as possible.
*   Remove references to the old documentation for V2.
=> [CXKB-939] Update the README for V2

internal/app/feed/exporter_report.go
We got an issue raised by one of customers related to report export failing in some cases.
After some investigation I found out for some reason they have `tabs` in the name of inspections and that causes the exporter to fail.
=> INTG-1686: remove tabs from the name

cmd/iauditor-exporter/cmd/export/export.go, internal/app/api/api.go, internal/app/api/api_test.go, internal/app/api/http_utils.go, internal/app/api/retry.go, internal/app/feed/export_feeds.go, internal/app/feed/export_feeds_intg_test.go, internal/app/feed/export_feeds_soak_test.go, internal/app/feed/export_feeds_test.go, internal/app/feed/exporter_report.go, internal/app/feed/exporter_report_test.go, internal/app/feed/feed.go, internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_inspection_item_test.go, internal/app/feed/feed_inspection_test.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_template_permission.go, internal/app/feed/feed_user.go, internal/app/inspections/inspections.go, internal/app/inspections/inspections_test.go
1. The current API’s returns x-rate-limit-reset in the response headers which refers to the Unix timestamp the next request will be allowed. Client will sleep until that time and retries again.
2. Added retries 5** errors.
=> [INTG-1667] Rate limiting and retry handling for all the API requests

internal/app/api/api.go, internal/app/api/api_test.go, internal/app/api/retry.go, internal/app/feed/feed_inspection_item.go
1. Ignoring 404 errors for all the API's.
2. Also ignoring 403 errors for some media objects. This happens if we upload `svg` files.  These files can be uploaded by frontend, but will be blocked by api-media and thus resulting with forbidden errors.
=> [INTG-1667] Ignore 404 errors for all the API's

.github/workflows/goreleaser.yml, .github/workflows/tests.yml, .goreleaser.yml, Makefile
I have tested the release process locally and it works, will test the ARM binary this evening on my machine at home to make sure it actually works.
=> Upgrade go to 1.16, add support for building ARM64 binaries for darwin

cmd/iauditor-exporter/cmd/export/export.go, cmd/iauditor-exporter/cmd/root.go, internal/app/feed/exporter_report.go, internal/app/feed/exporter_report_test.go, internal/app/feed/utils_test.go
added filename flag for the inspection report command
=> [INTG-1762] iauditor-exporter Allow specifying inspection ID or name when saving PDF/Word files

cmd/iauditor-exporter/cmd/configure_test.go
Add test case to make sure no errors are thrown when "iauditor-exporter configure" command is run
=> [INTG-1773] Smoke test for iauditor-exporter cmd

internal/app/api/api.go
While calculating media_id from the media_url we use to do string manipulation.
Changed that logic to get the id after the last "/"
=> [PROBLEM-872] Fix media ID logic

internal/app/feed/exporter_sql.go
Slow query logging threshold was set to 1 second for SQL.
Some customers experience slower times which causes lots of messages in the logs and potentially making those log files much bigger.
I have updated the threshold to 30 seconds.
=> INTG-1840: increase slow query logging threshold

internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_template.go
When starting the export we read the last `modified_at` value from related table. In situations that there is a large amount of data in those tables, this process can take some time to complete.
These indexes will greatly improve the performance of the query that reads `modified_at`.
=> INTG-1855: add indexes to improve performance

cmd/iauditor-exporter/cmd/export/export.go, cmd/iauditor-exporter/cmd/root.go, internal/app/feed/exporter_csv.go, internal/app/feed/exporter_csv_test.go, internal/app/feed/utils_test.go
- Introduced a new flag for `csv` export called `--max-rows-per-file` with the default value of `1000000`
- Cleanup all `csv` files for a feed before saving new files
- If  limit is reached, current file will be renamed to `feedName_20060102150405.999999.csv` and a new `feedName.csv` will be created
- The coverage is at `82%`. The code paths that are not covered are related to file system errors which I'm not sure how to test.
=> INTG-1841: add max row per file flag for csv

internal/app/feed/exporter_report.go
The name of the inspection isn't really helpful here, the ID is far more useful.
=> [PROBLEM-955] Log inspection ID instead of name when reporting errors

internal/app/feed/feed_action.go, internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_template_permission.go, internal/app/feed/feed_user.go
When not specifying a column size `gorm` by default uses `nvarchar(max)` which causes issues when customers are trying to add indexes to those columns.
I've updated most columns to have a fixed size when possible.
=> INTG-1867: make columns fixed size

internal/app/feed/feed_action_assignees.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_site.go
For each table we specify the columns that can be updated in the corresponding feed_table.go.
If the column is missing then it only inserts and doesn't update the data. Updated those columns through this PR.
=> [INTG-1937] Site_id from Inspections data set not updating

internal/app/feed/feed_action_assignee_test.go, internal/app/feed/feed_action_assignees.go
It looks like the inner loop when fetching the `actionID` for each row would overflow when `i+j` would exceed `len(rows)`. Adding a secondary check for the row array length to avoid this.
=> [PROBLEM-1079] fixing inner loop in actions_assignees

cmd/iauditor-exporter/cmd/export/export.go, cmd/iauditor-exporter/cmd/root.go, docs/iauditor-exporter_report.md
The "report preference" feature is being renamed to "report layout". Beyond our support articles, we also need to update other product areas to use the new feature name.
=> [KB-1787] Rename "Preference" to "Layout" in other product areas

Makefile
The author moved from Docker Hub to Github Repos for their images https://github.com/troian/golang-cross#docker
=> Fix docker repo for golang-cross

internal/app/api/api.go, internal/app/api/api_test.go, internal/app/api/http_utils.go, internal/app/api/retry.go
The API is actually using `X-RateLimit-Reset` not `X-Rate-Limit-Reset`. It also returns a number of seconds NOT an epoch time.
This also adjusts the code to user `Header.Get`, instead of accessing the map directly. As this does not behave correctly when header keys are lowercased.
=> [INTG-2028] Use correct rate limiting header

internal/app/feed/feed_inspection_item.go
Exporting to CSV when `media = true` can lead to false impression that the exporter is stuck.
Adding more logs, makes the iAuditorExporter actions more clear
=> INTG-2235 added logging when media is downloading

internal/app/api/api.go, internal/app/api/http_utils.go, internal/app/feed/feed_action.go, internal/app/feed/feed_group.go, internal/app/feed/feed_group_user.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_issue.go, internal/app/feed/feed_schedule.go, internal/app/feed/feed_schedule_assginee.go, internal/app/feed/feed_schedule_occurrence.go, internal/app/feed/feed_site.go, internal/app/feed/feed_template.go, internal/app/feed/feed_template_permission.go, internal/app/feed/feed_user.go
To properly analyse customer complaints related to the slowness, I added logs around HTTP calls
2022-05-11T11:20:05.889+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 147 remaining. Last call was 903ms
2022-05-11T11:20:08.290+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 127 remaining. Last call was 877ms
2022-05-11T11:20:10.994+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 107 remaining. Last call was 929ms
2022-05-11T11:20:13.149+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 87 remaining. Last call was 682ms
2022-05-11T11:20:16.999+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 67 remaining. Last call was 493ms
2022-05-11T11:20:19.861+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 47 remaining. Last call was 869ms …
=> [INTG-2277] add logs around http duration

.github/workflows/goreleaser.yml, .github/workflows/tests.yml, internal/app/feed/export_feeds.go, internal/app/feed/exporter_csv.go, internal/app/feed/exporter_report.go, internal/app/feed/exporter_schema.go, internal/app/feed/exporter_sql.go, internal/app/feed/feed.go, internal/app/feed/feed_action.go, internal/app/feed/feed_inspection.go, internal/app/feed/feed_inspection_item.go, internal/app/feed/feed_test.go
Added logs to SQL writes for actions/inspections/inspection_items
`2022-05-16T15:13:35.825+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 114 remaining. Last http call was 965ms. Last export operation was 34ms.
2022-05-16T15:13:38.328+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 94 remaining. Last http call was 906ms. Last export operation was 72ms.
2022-05-16T15:13:40.986+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 74 remaining. Last http call was 991ms. Last export operation was 58ms.
2022-05-16T15:13:43.260+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 54 remaining. Last http call was 789ms. Last export operation was 42ms.
2022-05-16T15:13:46.214+1000	INFO	iauditor-exporter@0.0.0-dev	inspection_items: 34 remaining. Last http call was 1220ms. …
=> [INTG-2277] add logs to actions, inspections, and inspection_items

Makefile
There is a bug in goreleaser 1.9.0 that is fixed in 1.9.2, however Golang cross has not pulled this in yet. Reverting for now so we can release.
https://github.com/SafetyCulture/iauditor-exporter/runs/6748337684?check_suite_focus=true#step:5:124
=> Pin GOLANG_CROSS_VERSION

internal/app/api/api_test.go, internal/app/feed/export_csv_local_test.go, internal/app/feed/export_feeds_intg_test.go, internal/app/feed/export_feeds_soak_test.go, internal/app/feed/export_feeds_test.go, internal/app/feed/exporter_csv_test.go, internal/app/feed/exporter_report_test.go, internal/app/feed/exporter_schema_test.go, internal/app/feed/exporter_sql_intg_test.go, internal/app/feed/exporter_sql_test.go, internal/app/feed/feed_action_assignee_test.go, internal/app/feed/feed_actions_test.go, internal/app/feed/feed_inspection_item_test.go, internal/app/feed/feed_inspection_test.go, internal/app/feed/feed_issue_test.go, internal/app/feed/utils_test.go, internal/app/inspections/inspections_test.go
`assert.Nil` logs an error that is just a pointer ref. `assert.NoError` logs the actual error.
=> [CSE-50] Improve errors returned from failed tests

cmd/safetyculture-exporter/cmd/export/export.go, cmd/safetyculture-exporter/cmd/root.go, pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go
better error messages when configuration file is missing or is corrupted
=> INTG-2620 process missing or corrupt yaml

pkg/internal/feed/feed_sheqsy_activity.go, pkg/internal/feed/feed_sheqsy_department.go, pkg/internal/feed/feed_sheqsy_department_employee.go, pkg/internal/feed/feed_sheqsy_employee.go
- Update Sheqsy UUID to size 36, tested it with csv and the databases we currently support
https://user-images.githubusercontent.com/95192827/220221226-bb0e49f6-f4fe-4fea-8293-eb3ab74a6205.mov
- believe no user is using Sheqsy. This fix does the db column change directly but if the user did Sheqsy export before and has data already, they might see the following records, such as activity table.
=> INTG-2689 Update Sheqsy UUID to size 36

pkg/api/mock_feeds_test.go, pkg/api/mocks/set_1/actions_deleted_single_page.json, pkg/api/mocks/set_1/outputs/actions.csv, pkg/api/mocks/set_2/outputs/actions.csv, pkg/api/utils_test.go, pkg/httpapi/models.go, pkg/internal/feed/feed_action.go, pkg/internal/feed/feed_inspection.go, pkg/internal/feed/fixtures/schemas/formatted/actions.txt
This uses our activity log to capture deleted actions and mark them as deleted in the export.
As deleted actions are no longer returned in the data feeds, they remain in exported data sets.
---
=> [CSE-68] Mark deleted actions as deleted from export

pkg/logger/logger.go
This adds the exporter version back to the log files. This is useful when we are sent logs to know what version of the tool a customer is running.
---
=> Add version back to log files

pkg/api/mocks/set_1/outputs/schedule_occurrences.csv, pkg/api/mocks/set_1/schemas/schedule_occurrences.csv, pkg/api/mocks/set_2/outputs/schedule_occurrences.csv, pkg/internal/feed/feed_schedule_occurrence.go, pkg/internal/feed/fixtures/schemas/formatted/schedule_occurrences.txt
=> INTG-3307 - adding `note` to schedule occurence feed.

Makefile, cmd/safetyculture-exporter/cmd/root.go, pkg/api/configuration_manager.go, pkg/api/configuration_manager_test.go, pkg/api/fixtures/invalid_block_size.yaml, pkg/api/fixtures/modified_before_after_conflict.yaml, pkg/api/fixtures/valid_with_block_size.yaml, pkg/api/fixtures/valid_with_modified_before.yaml, pkg/httpapi/models.go, pkg/internal/feed/drain_feed.go, pkg/internal/feed/feed_exporter.go, pkg/internal/feed/feed_inspection.go, pkg/internal/feed/feed_inspection_item.go, pkg/internal/inspections/inspections.go, pkg/internal/util/time_utils.go, pkg/internal/util/time_utils_test.go
**Note**: my first attempt at contributing to this repo; please point out anything I did wrong :) 
Allows to specify two parameters specific for `inspections` and`inspection_items` feeds only: 
- `modified_before`: to only export items modified before a certain date
- `block_size`: splits the total export range into smaller blocks, and then exports inspections one block at a time. Possible values (does't have to be 1, any integer should work): 
- `1d` for 1 day
- `1w` for 1 week
- `1m` for 1 month
- `1y` for 1 year at a time
If none of the new parameters are specified, it keeps the existing behaviour.
When inspections API processes calls for the inspections or inspection items feed, as a part of the call it counts all inspections in the remaining range.
For large organisations and export …
=> [CAPTURE-12136] Performance optimisation for inspections feeds for large organisations
